# Generated by Django 6.0.2 on 2026-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_tag_scope"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.ManyToManyField(
                to="articles.article", verbose_name="Название"
            ),
        ),
    ]
