# Generated by Django 6.0.2 on 2026-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(through="articles.Scope", to="articles.tag"),
        ),
        migrations.AddField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основной раздел"),
        ),
    ]
