# Generated by Django 6.0.2 on 2026-03-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_tag_options_remove_tag_name_article_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
