# Generated by Django 6.0.3 on 2026-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(
                related_name="article", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
